// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klimiokqqfrgzkzdyzae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsaW1pb2txcWZyZ3premR5emFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMzg3ODYsImV4cCI6MjA1NTkxNDc4Nn0.HMu5C4jXNUpJW-Pj61PuMmcdKGYqD3eAkhuCeqTiSuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);